# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Usuário do telegram', max_length=50, verbose_name='Usuário')),
                ('descricao', models.TextField(help_text='Descrição do usuário', verbose_name='Descrição')),
            ],
        ),
        migrations.DeleteModel(
            name='Technical',
        ),
    ]
