# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170102_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Número serial', max_length=100, verbose_name='Serial')),
                ('latitude', models.CharField(help_text='Coordenada de latitude', max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(help_text='Coordenada de longitude', max_length=100, verbose_name='Longitude')),
                ('ip', models.GenericIPAddressField(help_text='Endereço de rede', verbose_name='IP')),
                ('atualizacao', models.DateTimeField(help_text='Última atualização', verbose_name='Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Número serial', max_length=100, verbose_name='Serial')),
                ('estado', models.BooleanField(help_text='Estado da lâmpada', verbose_name='Estado')),
                ('dimerizacao', models.PositiveSmallIntegerField(help_text='Nível de dimerização', verbose_name='Dismerização')),
                ('potencia', models.PositiveIntegerField(help_text='Potência atual', verbose_name='Potência')),
                ('tensao', models.PositiveIntegerField(help_text='Tensão atual', verbose_name='Tensão')),
                ('corrente', models.PositiveIntegerField(help_text='Corrente atual', verbose_name='Corrente')),
                ('fase', models.PositiveIntegerField(help_text='Fase atual', verbose_name='Fase')),
                ('latitude', models.CharField(help_text='Coordenada de latitude', max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(help_text='Coordenada de longitude', max_length=100, verbose_name='Longitude')),
                ('ip', models.GenericIPAddressField(help_text='Endereço de rede', verbose_name='IP')),
                ('atualizacao', models.DateTimeField(help_text='Última atualização', verbose_name='Atualização')),
                ('concentrador', models.ForeignKey(help_text='Concentrador relacionado', on_delete=django.db.models.deletion.CASCADE, to='web.Concentrador')),
            ],
        ),
        migrations.CreateModel(
            name='Programar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(help_text='Horário de início', verbose_name='Início')),
                ('fim', models.DateTimeField(help_text='Horário de término', verbose_name='Fim')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramarDimerizacao',
            fields=[
                ('programar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Programar')),
                ('nivel', models.PositiveSmallIntegerField(help_text='Nível de dimerização', verbose_name='Nível')),
            ],
            bases=('web.programar',),
        ),
        migrations.CreateModel(
            name='ProgramarEstado',
            fields=[
                ('programar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Programar')),
                ('acao', models.CharField(choices=[('ON', 'Ligar'), ('OFF', 'Desligar')], help_text='Ação programada', max_length=3, verbose_name='Ação')),
            ],
            options={
                'ordering': ['dispositivo'],
            },
            bases=('web.programar',),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='programar_dimerizacao',
            field=models.ManyToManyField(blank=True, help_text='Programar dimerizacao relacionada', to='web.ProgramarDimerizacao'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='programar_estado',
            field=models.ManyToManyField(blank=True, help_text='Programar estado relacionada', to='web.ProgramarEstado'),
        ),
    ]
