# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170111_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programar',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='id',
        ),
        migrations.AddField(
            model_name='programar',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, help_text='Nome da programação', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concentrador',
            name='serial',
            field=models.CharField(help_text='Número serial', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(help_text='Número serial', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='usuario',
            field=models.CharField(help_text='Usuário do telegram', max_length=100, primary_key=True, serialize=False, verbose_name='Usuário'),
        ),
    ]
