# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170111_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programar',
            name='codigo',
            field=models.PositiveSmallIntegerField(help_text='Nome da programação', primary_key=True, serialize=False),
        ),
    ]
